@startuml callflow
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    AttributeIconSize 0
}
'skinparam style strictuml
skinparam stereotypeCBackgroundColor White
skinparam stereotypeIBackgroundColor White
skinparam stereotypeEBackgroundColor White
skinparam stereotypeABackgroundColor White
skinparam linetype ortho

'title "Basic Flow 1-to-1 (EXCEPTIONAL CASE)"
hide footbox

actor A
actor B

participant IM1
participant IM2

database DB
queue PUBSUB
queue "Message Store" AS QUEUE

A -> IM1 : connect
IM1 -> DB : location A
IM1 -> PUBSUB : SUBSCRIBE A

B -> IM2 : connect
IM2 -> DB : location B
IM2 -> PUBSUB : SUBSCRIBE B

A -> IM1 : "msg" B
IM1 -> DB ++ : Is B online?
return yes

IM1 -> QUEUE : LPUSH B "msg" (Backup)

IM1 -> PUBSUB : PUBLISH B "msg"

PUBSUB -> IM2 : "msg"

IM2 -> B : "msg"

B -> IM2 : "delivery"

IM2 -> QUEUE : DEL "msg"

IM2 -> PUBSUB : PUBLISH A "delivery"

PUBSUB -> IM1 : "delivery"

IM1 -> A : "delivery"

@enduml


