@startuml callflow
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    AttributeIconSize 0
}
'skinparam style strictuml
skinparam stereotypeCBackgroundColor White
skinparam stereotypeIBackgroundColor White
skinparam stereotypeEBackgroundColor White
skinparam stereotypeABackgroundColor White
skinparam linetype ortho

'title "Basic Flow 1-to-1 (PUBSUB))"
hide footbox

actor A
actor B
actor C

participant IM1
participant IM2
participant IM3

database DB 

queue PUBSUB


A -> IM1 !! : offline

== A is offline == 

B -> IM2 : "msg" for B in "g1"

IM2 -> IM2 : check A

note over IM2
if the receiver is offline, store in DB
end note


IM2 -> DB : store "msg"

A -> IM1 : connect (offline->online)

IM1 -> DB ++ : check stored messages
return "msg" of "g1"

note over A
A will have the first message 
for groupchat "g1" 
where A doen't have participant list of "g1"
end note

IM1 -> A : "msg" of "g1"

A -> A : no participant list of "g1"

note over A
A will make "JOIN" request 
in order to get participant list
end note


A -> IM1 : JOIN "g1" 

IM1 -> DB ++ : load participant list 
return participant list

IM1 -> A : NOTIFY participant list

note over A
A will overwrite participant list
using the newest list from the server
end note

A -> A : update participant list

A -> IM1 : "delivery"

IM1 -> PUBSUB : PUBLISH B "delivery"

PUBSUB -> IM2 : "delivery"

IM2 -> B : "delivery"

@enduml


