@startuml callflow
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    AttributeIconSize 0
}
'skinparam style strictuml
skinparam stereotypeCBackgroundColor White
skinparam stereotypeIBackgroundColor White
skinparam stereotypeEBackgroundColor White
skinparam stereotypeABackgroundColor White
skinparam linetype ortho

'title "Basic Flow 1-to-1 (PUBSUB))"
hide footbox

actor A
actor B
actor C


participant IM1
participant IM2
participant IM3

database DB 

queue PUBSUB

== The chat session was not exist any more in server ==

A -> IM1 : "msg" for "g1"

IM1 -> IM1 : no participant list of "g1"

IM1 -> DB ++: load participant list
return no participant list

IM1 -> A : "RESTART g1" 

note over A
"JOIN" event will be generated 
based on the call log after "RESTART"
end note

A -> IM1 : JOIN "g1" with participant list


IM1 -> IM1 : start reactivation 

IM1 -> DB : save participant list based on participant list of A
IM1 -> PUBSUB : SUBSCRIBE "g1"
IM1 -> PUBSUB : PUBLISH B "subscribe required for g1" 
PUBSUB -> IM2 : "subscribe required for groupID"
IM2 -> DB ++: load participant list
return participant list
IM2 -> PUBSUB: "SUBSCRIBE g1"

IM1 -> PUBSUB : PUBLISH C "subscribe requird for g1" 
PUBSUB -> IM3 : "subscribe required for g1"
IM3 -> DB ++: load participant list
return participant list
IM3 -> PUBSUB: "SUBSCRIBE g1"

== groupchat session is ready  == 

note over IM1
The stored message will be sent by PUBLISH
end note

IM1 -> PUBSUB : PUBLISH "g1" "msg"
PUBSUB -> IM2 : "msg"

IM2 -> B : "msg"
PUBSUB -> IM3 : "msg"
IM3 -> C : "msg"
@enduml


